"""
Every tunable constant in the game, in one place.

This module is deliberately data-only: no classes, no logic, no imports beyond
`os` for the two paths below. Everything else in the package reads from here via
`from .config import *`, which is why tuning the game never means opening a file
that also contains behaviour.

The star import is a considered choice rather than laziness. These names are read
constantly across the physics, spawn and draw code, and `config.GRAVITY` at every
call site buys nothing when the alternative is a module that provably cannot do
anything but bind constants. `__all__` at the bottom keeps the export surface
explicit.
"""
import os

# Paths are resolved from the package directory's parent -- the repo root -- so
# assets and the leaderboard are found the same way regardless of the working
# directory the game was launched from.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Sprite art: cropped from the "Dan the Man" asset packs (Playable Characters, Stage
# Hazards, Jetpack Joyride Event Cutscenes, Coin Counter, Charred Death Animation) plus
# a standalone coin icon (coin_ni_64.png). Loaded and scaled once in main(). Seeking
# missiles reuse a tinted duplicate of the straight-missile sprite (assets/missile_seeker.png,
# see draw_seeking_missile) rather than a primitive shape.
#
# Three sets are generated by their own scripts rather than cut straight from a sheet, each
# of which keeps its faceless/unmodified source art in assets/ so it can be re-run:
#   - the ground-running scientists (manager_run_00..07 + manager_down_00..03), by
#     tools/rebuild_manager_sprites.py -- frames off a scientist sheet with a photo head
#     on each;
#   - the straight missile (missile.png from missile_base.png), by
#     tools/rebuild_missile_sprite.py -- the same photo-head gag, on the nose of the
#     rocket. Note the *seeker* keeps the plain rocket, which is also what visually tells
#     the two missile types apart;
#   - the Profit Bird flap cycle (profit_bird_00..05 from profit_bird.png), by
#     tools/rebuild_profit_bird_sprites.py -- the one static pose cut up and re-posed.
#
# Provenance and licensing for every asset: see ASSET-CREDITS.md.
ASSET_DIR = os.path.join(_ROOT, "assets")

# Persistent (across runs of the program) leaderboard -- a simple JSON file next to
# the script, so it survives restarts but needs no external DB for a demo.
SCORES_PATH = os.path.join(_ROOT, "high_scores.json")
MAX_HIGH_SCORES = 5
MAX_NAME_LEN = 14

# Admin portal: a passcode-gated menu (Shift+Q between rounds) whose only action is wiping
# the saved leaderboard, so the board can be cleared between demo sessions without quitting
# the game or hunting down high_scores.json. Not a security boundary and not treated as
# one -- it exists so a wipe can't happen by a single stray keypress in front of an
# audience. It is deliberately never advertised on screen for the same reason.
ADMIN_PASSCODE = "admin"
ADMIN_MAX_INPUT = 16
ADMIN_MESSAGE_TIME = 2.0  # seconds the result line shows; a successful wipe then auto-closes


# ---------------------------------------------------------------------------
# DAQ I/O -- polls buttons / drives LEDs on a background thread so a slow or
# hiccuping DAQ read can never stall the pygame frame rate.
# ---------------------------------------------------------------------------
DEVICE = "Dev1"  # <-- update to match your device name in NI MAX
BUTTON_LINES = f"{DEVICE}/port0/line0:1"  # -> [Button 1, Button 2]
LED_LINES = f"{DEVICE}/port0/line6:7"     # -> [LED 1, LED 2]
DAQ_POLL_INTERVAL = 0.01  # seconds between DAQ reads/writes on the bg thread
DAQ_DEBUG_PRINT = True    # print raw DI reads to the terminal so wiring/polarity is easy to verify


# ---------------------------------------------------------------------------
# Game config
# ---------------------------------------------------------------------------
SCREEN_W, SCREEN_H = 1100, 640
FPS = 60
LANE_H = SCREEN_H // 2

# Display modes, cycled with F11. The game always renders to a fixed SCREEN_W x SCREEN_H
# canvas and that canvas is scaled to whatever the window happens to be as the very last
# step (see present()), so every mode is just a different window size -- no game logic,
# collision box, spawn coordinate or sprite scale is resolution-aware, and none of them
# had to change to support this.
DISPLAY_MODES = ("windowed", "borderless", "fullscreen")
DISPLAY_MODE_LABELS = {"windowed": "Windowed", "borderless": "Windowed Fullscreen",
                        "fullscreen": "Fullscreen"}

GRAVITY = 1500.0       # px/s^2, pulls player down
THRUST_ACCEL = 2400.0  # px/s^2, applied upward while thrusting (base, before boost/fuel)
MAX_FALL_SPEED = 640.0
MAX_RISE_SPEED = 480.0  # capped lower than fall speed so a boosted press can't rocket you into the ceiling

PLAYER_X = 150
PLAYER_SIZE = 32  # collision box; the sprite is drawn a touch larger than this, centered on it
PLAYER_SPRITE_H = 36  # rendered sprite height in px (width follows the source aspect ratio)

RUN_FRAME_COUNT = 10     # assets/run_00.png .. run_09.png -- played while not thrusting
RUN_FPS = 10.0
JETPACK_FRAME_COUNT = 5  # assets/jetpack_00.png .. jetpack_04.png -- played while thrusting
JETPACK_FPS = 9.0        # ping-ponged back and forth for a hover "wobble" instead of looping

# Death animation: assets/death_00.png .. death_03.png (Dan the Man "Charred Death"
# sheet, row 1). Plays once from the moment a player dies and freezes on the last
# (most-charred) frame, replacing the old flat dim-overlay effect.
DEATH_FRAME_COUNT = 4
DEATH_FPS = 9.0
DEATH_SPRITE_H = 46  # slightly larger than PLAYER_SPRITE_H -- the flame silhouette reads better bigger

# Profit Bird vehicle: assets/profit_bird_00..05.png -- a wing-flap cycle built out of the
# one static source pose by rebuild_profit_bird_sprites.py (it cuts the wing out, heals the
# belly behind it, and re-composites the wing at six angles).
#
# Unlike every other animation here it is *not* played off the global clock: the cycle runs
# once per flap from the player's own timer (Player.flap_anim_t) so the wings beat exactly
# when a press lifts the bird, which is what makes the flap read as the cause of the hop
# rather than as idle motion happening nearby. Frame 5 is the neutral glide pose, so a
# non-looping playback naturally settles there between flaps with no special-casing.
PROFIT_BIRD_FRAME_COUNT = 6
PROFIT_BIRD_FPS = 16.0
PROFIT_BIRD_FLAP_CYCLE = PROFIT_BIRD_FRAME_COUNT / PROFIT_BIRD_FPS  # seconds for one flap
# The generated frames carry vertical headroom for the downstroke (a 91px canvas around a
# 65px bird), so this is the *canvas* height, not the bird's -- it's larger than the old
# static sprite's 54 purely so the bird itself still draws at the same size on screen.
PROFIT_BIRD_SPRITE_H = 76

# Lil' Stomper vehicle: assets/lilstomper_00..05.png (a 6-frame walk/stomp cycle),
# looped the same way the run cycle loops.
STOMPER_FRAME_COUNT = 6
STOMPER_FPS = 7.0
STOMPER_SPRITE_H = 54

# Lil' Stomper control scheme: a tap is an instant "long jump" impulse (up to the same
# MAX_RISE_SPEED ceiling normal flight caps at); holding past that initial jump engages
# the jetpack for a brief, limited float from its own small tank (independent of the
# base jetpack's FUEL_MAX) instead of flying indefinitely.
STOMPER_FLOAT_ACCEL = 950.0       # px/s^2 upward while floating -- weaker than THRUST_ACCEL, a hover assist
STOMPER_FLOAT_FUEL_MAX = 1.1      # seconds of float assist per jump/ground-charge
STOMPER_FLOAT_REGEN_RATE = STOMPER_FLOAT_FUEL_MAX / 1.0  # only regenerates while grounded

# Profit Bird control scheme: Flappy-Bird-style -- each fresh press is a discrete
# upward hop (velocity set outright, not additive, same as the genre), no hold-to-fly
# and no fuel; gravity does the rest between hops.
PROFIT_BIRD_FLAP_SPEED = 420.0  # px/s upward impulse applied on each fresh press

# Start screen: both players hold their own button down together for this long to launch a
# round. A hold rather than a press so an idle fidget on the buttons -- or an audience
# member trying them out -- can't start a round before both players are actually ready.
START_HOLD_TIME = 2.0

# Fuel system: holding thrust continuously drains the tank; running dry cuts thrust
# off (you fall) until it's refilled by letting go. Matches the "~3s of hold" ask.
FUEL_MAX = 3.0                    # seconds of continuous thrust before empty
FUEL_REGEN_RATE = FUEL_MAX / 1.5  # refills faster than it drains while button is released

# Each fresh press (release -> press edge) gets a thrust multiplier from this list,
# indexed by how many presses deep into the current "streak" you are (clamped to the
# last entry beyond that). The streak resets once fuel fully refills, i.e. once you've
# rested long enough. This rewards a slight first kick and punishes rapid re-tapping,
# without being so strong that the first press alone rockets you into a zapper.
PRESS_BOOST_MULTIPLIERS = [1.2, 1.08, 1.0]

SCROLL_SPEED0 = 260.0  # px/s starting scroll speed
SCROLL_ACCEL = 4.0     # px/s^2, the lane speeds up over the run

# Vetted course seeds, chosen offline by tools/pick_course_seeds.py -- see that script for how
# difficulty is measured (it flies the player's own column down each candidate course and
# scores obstacle density, how narrow the openings are, and how much vertical travel they
# demand).
#
# A round used to draw an arbitrary randrange(2**31), which meant the course could land
# anywhere in the difficulty distribution, including the tail that ends a demo run in a
# few seconds in front of an audience. These 20 span the 2nd to 80th percentile of that
# distribution: still a genuine easy-to-hard spread and still randomly chosen per round,
# but with the punishing fifth dropped and the middle pulled below pure chance. They're
# deliberately unlabelled and unordered here -- nobody should be able to tell from the
# screen which end of the pool they drew.
COURSE_SEEDS = [
    748865093, 923201393, 1560552746, 1313872515, 1770307310,
    250808879, 1050363815, 18287115, 81630867, 39241983,
    256264942, 40006758, 877109647, 1249238150, 2056318671,
    1436087622, 1534474756, 1999077707, 1227472068, 245592881,
]

# Zappers: the staple hazard -- an electric beam strung between two emitter nodes,
# replacing the old single-sprite-stretched-to-a-random-box obstacle. Defined by two
# endpoints rather than a w/h box, so one class covers vertical, horizontal and diagonal
# beams at any length, and they spawn in hand-authored *patterns* (ZAPPER_PATTERNS)
# rather than one at a time -- a field to weave through instead of a row of lone blocks.
ZAPPER_NODE_FRAME_COUNT = 4    # assets/zapper_node_00..03.png
ZAPPER_NODE_FPS = 8.0
ZAPPER_NODE_SIZE = 20          # rendered emitter size (source art is ~20x20)
ZAPPER_ARC_FRAME_COUNT = 8     # assets/zapper_arc_g2_00..07.png -- the tileable beam segment
ZAPPER_ARC_FPS = 14.0          # fast, so beams crackle instead of sitting static
ZAPPER_ARC_H = 16              # rendered beam thickness
ZAPPER_EDGE_MARGIN = 6         # keeps emitter nodes just inside the lane edges
# Space left *after* a pattern before the next one begins. Wider than the old
# per-obstacle gap because a pattern is 150-320px across on its own, so without this the
# patterns would overlap into an unreadable wall.
ZAPPER_MIN_GAP, ZAPPER_MAX_GAP = 190, 320
# Every spawned pattern is verified to leave a vertical opening at least this tall at
# every x it covers -- enforced in code by pattern_is_passable(), not merely trusted to
# the authored numbers.
ZAPPER_MIN_GAP_H = PLAYER_SIZE * 2.5

# Missiles launch from off-screen right and fly straight left (same direction as the
# lane scroll), ignoring the player's position entirely (no tracking, that's a
# future feature). They never collide with zappers -- only with players. No missiles
# for the first 10-15s of a run, and spawn frequency ramps up as scroll_speed climbs.
MISSILE_W, MISSILE_H = 50, 20  # matches the aspect ratio of the missile sprite art
# Added on top of the lane's current scroll_speed (not absolute) so missiles always
# read as clearly faster than the scrolling zappers, no matter how far into a run.
MISSILE_SPEED_MIN, MISSILE_SPEED_MAX = 240.0, 320.0        # px/s, extra over scroll_speed
MISSILE_SPAWN_MIN, MISSILE_SPAWN_MAX = 2.5, 7.0            # seconds between spawns, per lane (fast/slow difficulty)
MISSILE_START_DELAY_MIN, MISSILE_START_DELAY_MAX = 10.0, 15.0  # seconds before the first missile of a run
MISSILE_DIFFICULTY_RANGE = 400.0  # scroll_speed increase (px/s) over which spawn gap ramps from MAX to MIN
# Every straight missile is now preceded by an exclamation-point telegraph pinned to the
# right edge of the lane at the y it will fire from -- the original never fires one
# unannounced. The missile object doesn't exist at all until the warning elapses, so
# there is nothing to collide with while it shows.
MISSILE_WARN_TIME = 1.2           # seconds the telegraph shows before the missile fires
MISSILE_WARN_W, MISSILE_WARN_H = 26, 30
MISSILE_WARN_BLINK_HZ = 6.0       # on/off cycles per second

# Seeking missiles: a rarer, later-arriving hazard on its own per-lane timer, independent
# of the straight-line Missile timer above so both types can appear in the same run.
# Reuses a tinted duplicate of the straight-missile sprite (see draw_seeking_missile).
SEEKER_W, SEEKER_H = 46, 22
# Spawns visible at the right edge (not deep off-screen like straight missiles) so the
# blink telegraph below is actually visible as a warning before it launches.
SEEKER_SPEED_MIN, SEEKER_SPEED_MAX = 260.0, 340.0             # px/s, extra over scroll_speed once launched
SEEKER_SPAWN_MIN, SEEKER_SPAWN_MAX = 9.0, 18.0                 # seconds between seekers -- rarer than straight missiles
SEEKER_START_DELAY_MIN, SEEKER_START_DELAY_MAX = 22.0, 30.0    # later than straight missiles' 10-15s
SEEKER_DIFFICULTY_RANGE = 550.0
SEEKER_BLINK_COUNT = 3       # full on/off blinks before launch
SEEKER_BLINK_INTERVAL = 0.27  # seconds per blink half-cycle (on or off)
SEEKER_MAX_VY = 220.0         # px/s cap on homing vertical speed -- kept well under player fall/rise
                               # speed so a last-second dodge can always outrun the turn
SEEKER_TURN_RATE = 900.0      # px/s^2 max rate vy can change -- gives it a turn radius instead of a snap
SEEKER_STEER_GAIN = 4.0       # converts y-distance-to-player into desired vy (clamped to SEEKER_MAX_VY)

# Vehicle power-ups (Profit Bird / Lil' Stomper, simplified): a token grants temporary
# invulnerability; a hit while active knocks the player out of the vehicle instead of
# killing them. In-lane pickup uses assets/vehicle_token.png (tinted per kind) for both
# vehicle kinds -- only Profit Bird has a dedicated in-vehicle player sprite so far
# (assets/profit_bird.png); Lil' Stomper still uses a tinted recolor of the base sprite.
TOKEN_W, TOKEN_H = 30, 30
TOKEN_SPAWN_MIN, TOKEN_SPAWN_MAX = 13.0, 20.0
VEHICLE_DURATION = 6.5         # seconds of invulnerability once picked up
VEHICLE_KINDS = ("profit_bird", "lil_stomper")
VEHICLE_COLORS = {"profit_bird": (255, 205, 60), "lil_stomper": (150, 205, 255)}
VEHICLE_LABELS = {"profit_bird": "PROFIT BIRD", "lil_stomper": "LIL' STOMPER"}
PROFIT_BIRD_DISTANCE_MULT = 1.5    # brief "speed boost" -- distance accrues faster while active
STOMPER_CEILING_FRAC = 0.55        # ground-hugging cap: can't climb above this fraction of the lane
HIT_GRACE_PERIOD = 0.5             # seconds of invulnerability right after a vehicle absorbs a hit,
                                    # so losing the vehicle can't immediately chain into a fatal hit
                                    # from the same hazard on the very next frame

# Picking up a vehicle token detonates every zapper/missile/seeker currently in that
# lane (Lane.detonate_hazards()) -- doesn't pause or end the run, just clears the
# immediate area so the reward isn't immediately undone by whatever's already in flight.
EXPLOSION_DURATION = 0.45  # seconds an individual blast VFX plays for
EXPLOSION_MAX_RADIUS = 34

# Coins: small, frequent, non-hazard collectibles -- track a running count per player,
# separate from the distance score. Uses assets/coin_ni_64.png.
COIN_W, COIN_H = 20, 20
COIN_SPACING = 34            # px between coin centres along a formation
COIN_MIN_COUNT, COIN_MAX_COUNT = 5, 10
COIN_ARC_HEIGHT_MIN, COIN_ARC_HEIGHT_MAX = 60, 130  # vertical travel of the curved shapes
COIN_FORMATION_TRIES = 6     # vertical offsets attempted before giving up on a spawn
# Clear space kept between a coin and a beam. Half the beam's drawn thickness (collision
# treats a beam as a zero-width segment) plus a visible margin on top.
COIN_CLEARANCE = ZAPPER_ARC_H // 2 + 7
# Per *formation* now, not per coin -- a formation is 5-10 coins and up to ~300px long,
# so the old 1.1-2.3s single-coin cadence would have run them into each other.
COIN_SPAWN_MIN, COIN_SPAWN_MAX = 3.2, 5.6

# Scientists: ground-running bystanders and a *reward*, not a hazard -- running into one
# knocks it over for bonus coins and never damages the player. Deliberately kept out of
# Lane.hazards() (which feeds the kill logic) and collision-checked on their own path.
SCIENTIST_SPRITE_H = 46   # rendered sprite height; the source frames carry transparent
                           # padding, so the *visible* scientist lands near the player's size
SCIENTIST_W, SCIENTIST_H = 22, 34  # collision box, tuned to the visible body rather than the
                                    # padded canvas -- generous, since catching one is the reward
# The source frames leave roughly a fifth of the canvas as empty space beneath the feet;
# the sprite is nudged down by that much at draw time so a ground-anchored scientist
# actually stands on the lane floor instead of hovering above it (see draw_scientist).
SCIENTIST_FOOT_PAD = round(SCIENTIST_SPRITE_H * 0.20)
SCIENTIST_RUN_FRAME_COUNT = 8   # assets/manager_run_00.png .. manager_run_07.png, loops
SCIENTIST_RUN_FPS = 10.0
SCIENTIST_DOWN_FRAME_COUNT = 4  # assets/manager_down_00.png .. manager_down_03.png, plays once
SCIENTIST_DOWN_FPS = 9.0
# Fraction of the lane's scroll_speed a *running* scientist moves at. Under 1.0, so it
# travels the same direction as the scroll but slower than the scenery -- i.e. in world
# terms it's fleeing the same way the player flies, just not fast enough, which is what
# makes it drift back into the player. Once knocked over it stops running and rides the
# lane at the full scroll speed like any other scenery.
SCIENTIST_SPEED_FRAC = 0.75
SCIENTIST_SPAWN_MIN, SCIENTIST_SPAWN_MAX = 3.5, 7.5  # seconds between spawns, per lane
SCIENTIST_KNOCKED_HOLD = 0.7   # seconds the final knocked frame holds before despawning
SCIENTIST_BONUS_COINS = 3      # counted as coins so it feeds the existing coin leaderboard,
                                # not the distance score

# Floating "+N" feedback popped on a scientist knockdown -- purely visual, lane-owned so
# it scrolls along with everything else (same as Explosion).
POPUP_DURATION = 0.7
POPUP_RISE = 26        # px the text floats upward over its lifetime
POPUP_COLOR = (255, 220, 90)

WHITE = (240, 240, 240)
BLACK = (15, 15, 15)
LANE_BG = [(35, 40, 55), (30, 34, 48)]  # translucent tint over assets/background.png, not an opaque fill
PLAYER_COLORS = [(80, 200, 255), (255, 150, 80)]
THRUST_COLOR = (255, 220, 90)
FUEL_BAR_COLOR = (90, 220, 140)
FUEL_BAR_EMPTY_COLOR = (70, 70, 80)


__all__ = [_n for _n in dir() if not _n.startswith("_") and _n != "os"]
