"""
The game loop: state machine, input routing, collision, and the draw order.

This is the only module that knows about all the others, and deliberately the only
place where the question "where did this input come from?" is answered. Everything
downstream -- `Player.update`, every mechanic built on it -- receives a plain bool.

The loop is a flat `while running` with three phases per frame: drain the SDL event
queue, advance whichever state is live ("enter_names" or "playing", with the admin
modal as a flag over either), then draw. Game-over is not a separate state; it is
"playing" with both players dead, which is why the restart and leaderboard checks
live inside that branch.
"""
import os
import random
import sys
import time

import pygame

from .config import *
from .daq import DaqIO
from .entities import Player
from .lane import Lane
from .render import (anim_frame, apply_display_mode, draw_coin, draw_explosion,
                     draw_missile, draw_missile_warning, draw_player, draw_scientist,
                     draw_score_popup, draw_seeking_missile, draw_text_center,
                     draw_vehicle_player, draw_vehicle_token, draw_zapper,
                     lighten, load_scaled_sprite, present, tinted_sprite)
from .scores import add_high_scores, clear_high_scores, draw_high_scores, load_high_scores
from .ui import draw_admin_portal, draw_name_entry, draw_start_hold


def main():
    """Sets up the window, loads every sprite, then runs the loop until quit.

    All state lives in locals here rather than in a `Game` object, and the handful
    of state transitions are closures over them. For a loop this size that trades a
    little testability for the property that there is exactly one place to look to
    know what the game is currently doing -- no field can be mutated from somewhere
    off-screen. The tradeoff is real and it is why the DEVLOG's end-to-end tests had
    to wrap the module-level draw functions to observe which screen was live.

    Sprites are loaded eagerly, before the loop, so a missing or corrupt asset fails
    immediately at startup rather than at the moment the entity first spawns --
    which for a seeker would be thirty seconds into a demo in front of an audience.
    """
    pygame.init()
    pygame.display.set_caption("Two-Player Jetpack Joyride Demo")
    # Captured before any window exists -- once we're in fullscreen, a display query
    # would report the window's size rather than the desktop's.
    desktop_size = pygame.display.get_desktop_sizes()[0]
    display_mode = DISPLAY_MODES[0]
    window = apply_display_mode(display_mode, desktop_size)
    # Everything draws here at a fixed size, whatever the window is doing.
    canvas = pygame.Surface((SCREEN_W, SCREEN_H))
    clock = pygame.time.Clock()
    font_big = pygame.font.SysFont("consolas", 48, bold=True)
    font_med = pygame.font.SysFont("consolas", 28, bold=True)
    font_small = pygame.font.SysFont("consolas", 20)

    p2_tint = lighten(PLAYER_COLORS[1], 0.55)  # gentle tint -- a raw multiply crushed everything to red
    run_frames_base = [load_scaled_sprite(os.path.join(ASSET_DIR, f"run_{i:02d}.png"), PLAYER_SPRITE_H)
                        for i in range(RUN_FRAME_COUNT)]
    jetpack_frames_base = [load_scaled_sprite(os.path.join(ASSET_DIR, f"jetpack_{i:02d}.png"), PLAYER_SPRITE_H)
                            for i in range(JETPACK_FRAME_COUNT)]
    run_frames = [run_frames_base, [tinted_sprite(f, p2_tint) for f in run_frames_base]]
    jetpack_frames = [jetpack_frames_base, [tinted_sprite(f, p2_tint) for f in jetpack_frames_base]]

    death_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"death_{i:02d}.png"), DEATH_SPRITE_H)
                     for i in range(DEATH_FRAME_COUNT)]

    # Vehicle-mode sprite swaps -- both real animation cycles now: Profit Bird's 6-frame
    # wing flap (played once per press, see PROFIT_BIRD_FRAME_COUNT) and Lil' Stomper's
    # 6-frame walk. The bird's frames are generated by tools/rebuild_profit_bird_sprites.py from
    # assets/profit_bird.png, which is kept around as that script's source art.
    profit_bird_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"profit_bird_{i:02d}.png"),
                                              PROFIT_BIRD_SPRITE_H)
                           for i in range(PROFIT_BIRD_FRAME_COUNT)]
    stomper_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"lilstomper_{i:02d}.png"), STOMPER_SPRITE_H)
                       for i in range(STOMPER_FRAME_COUNT)]

    # Vehicle token pickup uses one shared icon (assets/vehicle_token.png) -- kind is
    # communicated with a color halo (see draw_vehicle_token) rather than tinting the
    # coin's own pixels, since multiplying a mostly-gold sprite by a blue-ish tint just
    # crushes it to a muddy gray instead of reading as blue.
    vehicle_token_sprite = load_scaled_sprite(os.path.join(ASSET_DIR, "vehicle_token.png"), TOKEN_H)

    coin_sprite = load_scaled_sprite(os.path.join(ASSET_DIR, "coin_ni_64.png"), COIN_H)

    # Scientists are world objects (like zappers and coins), so unlike the player frames
    # they aren't tinted per lane -- both lanes share one set.
    scientist_run_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"manager_run_{i:02d}.png"),
                                                SCIENTIST_SPRITE_H)
                             for i in range(SCIENTIST_RUN_FRAME_COUNT)]
    scientist_down_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"manager_down_{i:02d}.png"),
                                                 SCIENTIST_SPRITE_H)
                              for i in range(SCIENTIST_DOWN_FRAME_COUNT)]

    missile_sprite = load_scaled_sprite(os.path.join(ASSET_DIR, "missile.png"), MISSILE_H + 4)

    # Zapper art, cut from the Stage Hazards sheet. The arc frames are the *tileable*
    # beam segment (uniform 22px source width, seamless butted end-to-end); the other
    # extracted set on that sheet is the emitter burst, and zapper_full_*.png is a fixed
    # 118px pre-assembled zapper kept as reference art -- neither is used here, since
    # building from nodes + a tiled beam is what allows arbitrary length and angle.
    zapper_node_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"zapper_node_{i:02d}.png"),
                                              ZAPPER_NODE_SIZE)
                           for i in range(ZAPPER_NODE_FRAME_COUNT)]
    zapper_arc_frames = [load_scaled_sprite(os.path.join(ASSET_DIR, f"zapper_arc_g2_{i:02d}.png"),
                                             ZAPPER_ARC_H)
                          for i in range(ZAPPER_ARC_FRAME_COUNT)]

    # Seeking missiles: a duplicate of the straight-missile art (assets/missile_seeker.png),
    # tinted per state so the blink telegraph (orange) vs. armed/launched (red) distinction
    # from the old placeholder chevron still reads, just on a real sprite now.
    seeker_sprite_base = load_scaled_sprite(os.path.join(ASSET_DIR, "missile_seeker.png"), SEEKER_H + 6)
    seeker_sprite_telegraph = tinted_sprite(seeker_sprite_base, lighten((255, 140, 60), 0.35))
    seeker_sprite_armed = tinted_sprite(seeker_sprite_base, lighten((255, 60, 60), 0.35))

    background_sprite = pygame.image.load(os.path.join(ASSET_DIR, "background.png")).convert()
    background_sprite = pygame.transform.smoothscale(background_sprite, (SCREEN_W, SCREEN_H))
    # Translucent per-lane tint over the background -- keeps the two lanes visually
    # separated and hazards/text readable without fully hiding the artwork underneath.
    lane_overlays = []
    for color in LANE_BG:
        overlay = pygame.Surface((SCREEN_W, LANE_H), pygame.SRCALPHA)
        overlay.fill((*color, 165))
        lane_overlays.append(overlay)

    daq = DaqIO()

    lanes = [Lane(0, LANE_H), Lane(LANE_H, LANE_H)]
    players = [Player(0, 0, LANE_H), Player(1, LANE_H, LANE_H)]
    key_map = [pygame.K_SPACE, pygame.K_UP]

    round_seed = None

    def reset_game():
        """Draws one course seed and hands the same value to both lanes.

        This single line is the entire fair-race mechanism. Because a lane derives
        every spawn position and timing from its own seeded RNG, giving both lanes
        one seed makes the two courses byte-identical, and the only remaining
        difference between the players is what they do about it.
        """
        # One seed per round, shared by both lanes, so the two players race the exact
        # same course and the result is skill rather than who drew the kinder lane.
        #
        # Drawn from the vetted COURSE_SEEDS pool rather than the whole 2**31 space, and
        # never the same course twice running: with only 20 seeds, plain random choice
        # repeats back-to-back often enough over a demo session to look like a bug.
        nonlocal round_seed
        round_seed = random.choice([s for s in COURSE_SEEDS if s != round_seed]
                                    or COURSE_SEEDS)
        for lane in lanes:
            lane.reset(round_seed)
        for p in players:
            p.reset()

    high_scores = load_high_scores()
    player_names = ["Player 1", "Player 2"]
    name_inputs = ["", ""]
    active_field = 0
    scores_recorded = False
    state = "enter_names"  # "enter_names" or "playing" (game-over is just "playing" + both dead)
    pygame.key.start_text_input()  # on for name entry; turned off during "playing" (see below)

    # How long both inputs have been held on the start screen. `armed` gates that: it goes
    # False whenever we land on the name screen and only comes back once both inputs have
    # been seen released, so the both-buttons-held restart at game over can't roll straight
    # through the name screen into another round while the players are still holding.
    start_hold_t = 0.0
    start_hold_armed = True

    # Admin portal state. A flag rather than another `state` value: it's a modal drawn over
    # whichever screen is underneath, so making it a state would mean teaching the whole
    # draw path to remember what to render behind it.
    admin_open = False
    admin_input = ""
    admin_message = ""
    admin_message_ok = False
    admin_message_t = 0.0
    admin_swallow_text = False

    def go_to_name_entry():
        """Ends a round and returns to the name screen with both names prefilled.

        The single exit path from game over, shared by the R key and the
        both-buttons hold, so the text-input handoff below cannot be got right in
        one and forgotten in the other.
        """
        # Returning to name entry from game-over (via R or both-buttons-down). Re-enabling
        # text input here -- rather than leaving it on throughout "playing" -- is what stops
        # the R keypress that triggers this from also leaking an "r" into the name field:
        # while text input is off, SDL never generates a TEXTINPUT event for that keypress
        # in the first place, so there's nothing to leak regardless of event ordering.
        nonlocal name_inputs, active_field, state, start_hold_t, start_hold_armed
        name_inputs = [player_names[0], player_names[1]]  # prefilled, quick restart
        active_field = 0
        state = "enter_names"
        # Disarmed until both inputs are released: the both-buttons restart that gets here
        # is itself a both-buttons hold, so without this it would satisfy the hold-to-start
        # meter immediately and launch a round before anyone could retype a name.
        start_hold_t = 0.0
        start_hold_armed = False
        pygame.key.start_text_input()

    def start_game():
        """Launches a round. Reached from ENTER and from the hold-to-start meter."""
        nonlocal scores_recorded, state, start_hold_t
        player_names[0] = name_inputs[0].strip() or "Player 1"
        player_names[1] = name_inputs[1].strip() or "Player 2"
        reset_game()
        scores_recorded = False
        state = "playing"
        start_hold_t = 0.0
        pygame.key.stop_text_input()  # stops KEYDOWN presses during play (e.g. R) from
                                       # also generating a TEXTINPUT event

    def open_admin_portal():
        """Opens the leaderboard-wipe modal over whatever screen is showing.

        A flag rather than a `state` value: the modal draws over the screen beneath
        it, so making it a state would require the whole draw path to remember what
        to render behind it.
        """
        nonlocal admin_open, admin_input, admin_message, admin_swallow_text, start_hold_t
        admin_open = True
        admin_input = ""
        admin_message = ""
        start_hold_t = 0.0  # a hold in progress shouldn't keep charging behind the modal
        # On the name screen text input is already live, so SDL still delivers a TEXTINPUT
        # for the very 'Q' that opened this -- swallow exactly that one so the passcode
        # field doesn't start with a stray character. Opened from game over, text input is
        # off and that press generates nothing, so there is nothing to swallow.
        admin_swallow_text = state == "enter_names"
        pygame.key.start_text_input()

    def close_admin_portal():
        """Dismisses the modal and returns text input to the screen underneath."""
        nonlocal admin_open
        admin_open = False
        # Hand text input back to whichever screen we're returning to: on during name
        # entry, off during play so R and friends don't double as TEXTINPUT events.
        if state == "enter_names":
            pygame.key.start_text_input()
        else:
            pygame.key.stop_text_input()

    def submit_admin_passcode():
        """Checks the typed passcode and wipes the board on a match.

        Accepts surrounding whitespace and any casing, because this is typed under
        demo conditions and a rejected passcode costs the operator far more than a
        lenient comparison does. It is not an access control -- see ADMIN_PASSCODE.
        """
        nonlocal high_scores, admin_input, admin_message, admin_message_ok, admin_message_t
        if admin_input.strip().lower() == ADMIN_PASSCODE:
            high_scores = clear_high_scores()
            admin_message, admin_message_ok = "LEADERBOARD RESET", True
        else:
            admin_message, admin_message_ok = "INCORRECT PASSCODE", False
        admin_message_t = 0.0
        admin_input = ""

    running = True
    while running:
        dt = min(clock.tick(FPS) / 1000.0, 0.05)  # clamp so a hiccup can't cause a physics jump

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.VIDEORESIZE and display_mode == "windowed":
                window = pygame.display.set_mode(event.size, pygame.RESIZABLE)
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_F11:
                    # Cycle windowed -> windowed fullscreen -> fullscreen. Handled before
                    # the state checks so it works on every screen, including mid-run.
                    display_mode = DISPLAY_MODES[(DISPLAY_MODES.index(display_mode) + 1)
                                                  % len(DISPLAY_MODES)]
                    window = apply_display_mode(display_mode, desktop_size)
                elif admin_open:
                    # Ahead of the global ESC-quits binding on purpose, so ESC backs out
                    # of the portal instead of quitting the game out from under it.
                    if event.key == pygame.K_ESCAPE:
                        close_admin_portal()
                    elif event.key == pygame.K_BACKSPACE:
                        admin_input = admin_input[:-1]
                    elif event.key in (pygame.K_RETURN, pygame.K_KP_ENTER):
                        submit_admin_passcode()
                elif event.key == pygame.K_ESCAPE:
                    running = False
                elif (event.key == pygame.K_q and event.mod & pygame.KMOD_SHIFT
                        and (state == "enter_names" or all(not p.alive for p in players))):
                    # Shift-modified so a plain 'q' still types into a name field -- the
                    # portal would otherwise make names like "Quinn" impossible to enter.
                    # Between rounds only (name entry or game over, the same guard the R
                    # restart uses), never mid-run where it would freeze a live race.
                    open_admin_portal()
                elif state == "enter_names":
                    if event.key == pygame.K_BACKSPACE:
                        name_inputs[active_field] = name_inputs[active_field][:-1]
                    elif event.key == pygame.K_TAB:
                        active_field = 1 - active_field
                    elif event.key in (pygame.K_RETURN, pygame.K_KP_ENTER):
                        start_game()
                elif state == "playing" and event.key == pygame.K_r and all(not p.alive for p in players):
                    go_to_name_entry()
            elif event.type == pygame.TEXTINPUT:
                if admin_open:
                    # Matched on both "is this the first character since the portal
                    # opened" and "is it actually a q", so that if SDL ever doesn't
                    # deliver that TEXTINPUT the flag can't go on to eat a real keystroke
                    # and turn the typed passcode into "dmin". Case-folded because the
                    # shifted hotkey arrives as "Q".
                    swallow, admin_swallow_text = admin_swallow_text, False
                    if swallow and event.text.lower() == "q":
                        pass  # the 'Q' that opened the portal
                    elif len(admin_input) < ADMIN_MAX_INPUT:
                        admin_input += event.text
                elif state == "enter_names" and len(name_inputs[active_field]) < MAX_NAME_LEN:
                    name_inputs[active_field] += event.text

        if admin_open:
            # The modal freezes whatever is underneath: no lane updates, no hold charging.
            daq.set_leds(False, False)
            if admin_message:
                admin_message_t += dt
                if admin_message_t >= ADMIN_MESSAGE_TIME:
                    if admin_message_ok:
                        close_admin_portal()  # wipe done and seen -- drop back to the game
                    admin_message = ""
        elif state == "playing":
            if daq.available:
                # Buttons are the primary input during the demo -- keyboard is ignored
                # so an audience member near a keyboard can't steal control.
                daq_b1, daq_b2 = daq.get_buttons()
                thrust = [daq_b1, daq_b2]
            else:
                # No DAQ connected -- fall back to keyboard for dev/testing.
                keys = pygame.key.get_pressed()
                thrust = [keys[key_map[0]], keys[key_map[1]]]

            for i, p in enumerate(players):
                p.update(dt, thrust[i], lanes[i].scroll_speed)
                lanes[i].update(dt, p.alive, p.y)
                if p.alive:
                    p_rect = p.rect()
                    if any(hazard.collides(p_rect) for hazard in lanes[i].hazards()):
                        p.on_hazard_hit()
                    tokens_hit = lanes[i].collect_tokens(p_rect)
                    for token in tokens_hit:
                        p.activate_vehicle(token.kind)
                    if tokens_hit:
                        # Clears the immediate area so the reward isn't undone by
                        # something already in flight the instant it's picked up.
                        lanes[i].detonate_hazards()
                    if p.vehicle_active and p.vehicle_kind == "profit_bird":
                        # Auto-collect: Profit Bird acts as a coin magnet for its lane.
                        p.coins += len(lanes[i].collect_all_coins())
                    else:
                        p.coins += len(lanes[i].collect_coins(p_rect))
                    # Scientists are a reward, so they get their own collision pass rather
                    # than riding on hazards() above -- running into one only knocks it
                    # over, never damages the player. Paid out in coins (not distance) so
                    # the bonus feeds the separate coin leaderboard.
                    p.coins += len(lanes[i].knock_over_scientists(p_rect)) * SCIENTIST_BONUS_COINS

            daq.set_leds(thrust[0] and players[0].alive, thrust[1] and players[1].alive)

            if all(not p.alive for p in players) and not scores_recorded:
                entries = [(player_names[i], players[i].distance, players[i].coins) for i in range(2)]
                high_scores = add_high_scores(high_scores, entries)
                scores_recorded = True

            # Alternate restart: both players' buttons held down together, once the
            # round is over -- same trigger as R, for a hands-on-the-buttons restart
            # that doesn't need reaching for the keyboard.
            if all(not p.alive for p in players) and thrust[0] and thrust[1]:
                go_to_name_entry()
        else:
            # Hold-to-start on the name screen: both players' buttons -- or both keyboard
            # fallbacks -- held together for START_HOLD_TIME launches the round, so a demo
            # runs start to finish from the buttons without anyone reaching for a keyboard.
            # Unlike gameplay this accepts the keyboard even with the DAQ connected: there's
            # no round in progress for a bystander's keypress to interfere with.
            daq_b1, daq_b2 = daq.get_buttons()
            keys = pygame.key.get_pressed()
            both_held = (daq_b1 and daq_b2) or (keys[key_map[0]] and keys[key_map[1]])
            daq.set_leds(both_held, both_held)  # hardware feedback that the hold registered
            if not both_held:
                start_hold_t = 0.0
                start_hold_armed = True  # released -- a fresh hold may start charging
            elif start_hold_armed:
                start_hold_t += dt
                if start_hold_t >= START_HOLD_TIME:
                    start_game()

        # ---- draw ----
        anim_t = pygame.time.get_ticks() / 1000.0
        canvas.blit(background_sprite, (0, 0))

        if state == "enter_names":
            dim = pygame.Surface((SCREEN_W, SCREEN_H), pygame.SRCALPHA)
            dim.fill((0, 0, 0, 120))
            canvas.blit(dim, (0, 0))
            draw_name_entry(canvas, font_big, font_med, font_small, name_inputs, active_field,
                             DISPLAY_MODE_LABELS[display_mode])
            draw_start_hold(canvas, font_small, start_hold_t / START_HOLD_TIME)
        else:
            for i, lane in enumerate(lanes):
                canvas.blit(lane_overlays[i], (0, lane.lane_top))
            pygame.draw.line(canvas, BLACK, (0, LANE_H), (SCREEN_W, LANE_H), 2)

            for i, (lane, p) in enumerate(zip(lanes, players)):
                for z in lane.zappers:
                    draw_zapper(canvas, z, anim_t, zapper_arc_frames, zapper_node_frames)
                for sci in lane.scientists:
                    draw_scientist(canvas, sci, scientist_run_frames, scientist_down_frames)
                for m in lane.missiles:
                    draw_missile(canvas, m, missile_sprite)
                for w in lane.missile_warnings:
                    draw_missile_warning(canvas, w, anim_t, lane.lane_top, lane.lane_h)
                for s in lane.seekers:
                    draw_seeking_missile(canvas, s, seeker_sprite_telegraph, seeker_sprite_armed)
                for c in lane.coins:
                    draw_coin(canvas, c, anim_t, coin_sprite)
                for tk in lane.tokens:
                    draw_vehicle_token(canvas, tk, anim_t, vehicle_token_sprite)
                for e in lane.explosions:
                    draw_explosion(canvas, e)
                for pop in lane.popups:
                    draw_score_popup(canvas, pop, font_med)

                if p.alive and p.vehicle_active and p.vehicle_kind == "profit_bird":
                    # Frames advance on the player's per-flap timer, not the global clock,
                    # and don't loop -- so the cycle fires on the press and settles on the
                    # glide frame until the next one.
                    draw_vehicle_player(canvas, p, anim_t, profit_bird_frames, PROFIT_BIRD_FPS,
                                         frame_t=p.flap_anim_t, loop=False)
                elif p.alive and p.vehicle_active and p.vehicle_kind == "lil_stomper":
                    draw_vehicle_player(canvas, p, anim_t, stomper_frames, STOMPER_FPS)
                else:
                    draw_player(canvas, p, anim_t, run_frames[i], jetpack_frames[i], death_frames)

                canvas.blit(font_med.render(f"{player_names[i]}: {int(p.distance)} m   {p.coins} coins", True, WHITE),
                            (16, lane.lane_top + 12))

                # Fuel bar -- shows Lil' Stomper's float-assist charge while that vehicle
                # is active (its own small tank), otherwise the base jetpack fuel.
                if p.vehicle_active and p.vehicle_kind == "lil_stomper":
                    fuel_frac = p.stomper_float_fuel / STOMPER_FLOAT_FUEL_MAX
                else:
                    fuel_frac = p.fuel / FUEL_MAX
                bar_x, bar_y, bar_w, bar_h = 16, lane.lane_top + 46, 140, 10
                pygame.draw.rect(canvas, FUEL_BAR_EMPTY_COLOR, (bar_x, bar_y, bar_w, bar_h), border_radius=4)
                fill_w = int(bar_w * fuel_frac)
                if fill_w > 0:
                    pygame.draw.rect(canvas, FUEL_BAR_COLOR, (bar_x, bar_y, fill_w, bar_h), border_radius=4)

                # Vehicle-mode timer bar, only shown while active
                if p.vehicle_active:
                    vbar_x, vbar_y, vbar_w, vbar_h = 16, lane.lane_top + 64, 140, 8
                    v_color = VEHICLE_COLORS[p.vehicle_kind]
                    pygame.draw.rect(canvas, FUEL_BAR_EMPTY_COLOR, (vbar_x, vbar_y, vbar_w, vbar_h), border_radius=4)
                    vfill_w = int(vbar_w * (p.vehicle_timer / VEHICLE_DURATION))
                    if vfill_w > 0:
                        pygame.draw.rect(canvas, v_color, (vbar_x, vbar_y, vfill_w, vbar_h), border_radius=4)
                    label = font_small.render(VEHICLE_LABELS[p.vehicle_kind], True, v_color)
                    canvas.blit(label, (vbar_x + vbar_w + 8, vbar_y - 6))

                if not p.alive:
                    draw_text_center(canvas, f"{player_names[i]} Down!", font_big, (255, 80, 80),
                                      (SCREEN_W // 2, lane.lane_top + lane.lane_h // 2))

            if all(not p.alive for p in players):
                d0, d1 = players[0].distance, players[1].distance
                if d0 > d1:
                    winner_text = f"{player_names[0]} Wins!"
                elif d1 > d0:
                    winner_text = f"{player_names[1]} Wins!"
                else:
                    winner_text = "It's a tie!"

                overlay = pygame.Surface((SCREEN_W, SCREEN_H), pygame.SRCALPHA)
                overlay.fill((0, 0, 0, 160))
                canvas.blit(overlay, (0, 0))
                draw_text_center(canvas, "GAME OVER", font_big, WHITE, (SCREEN_W // 2, SCREEN_H // 2 - 90))
                draw_text_center(canvas, winner_text, font_med, (255, 220, 90), (SCREEN_W // 2, SCREEN_H // 2 - 45))
                draw_text_center(
                    canvas,
                    f"{player_names[0]}: {int(d0)} m, {players[0].coins}c    "
                    f"{player_names[1]}: {int(d1)} m, {players[1].coins}c",
                    font_med, WHITE, (SCREEN_W // 2, SCREEN_H // 2 + 5))
                draw_text_center(canvas, "Press R -- or both buttons -- to play again", font_small, WHITE,
                                  (SCREEN_W // 2, SCREEN_H // 2 + 55))
                # Both lanes ran this seed, so it identifies the course both players
                # raced -- enough to reference or rerun a round later.
                draw_text_center(canvas, f"seed {round_seed}", font_small, (150, 150, 160),
                                  (SCREEN_W // 2, SCREEN_H // 2 + 88))

            hint = "DAQ: connected" if daq.available else "DAQ: not found (keyboard-only)"
            canvas.blit(font_small.render(hint, True, (160, 160, 160)), (SCREEN_W - 260, SCREEN_H - 28))
            canvas.blit(font_small.render(f"F11: {DISPLAY_MODE_LABELS[display_mode]}", True,
                                           (130, 130, 140)), (16, SCREEN_H - 28))

        draw_high_scores(canvas, font_small, font_small, high_scores)

        # Last, so the modal sits over the leaderboard it's about -- and over it lightly
        # enough that the board is still readable as it empties.
        if admin_open:
            draw_admin_portal(canvas, font_big, font_med, font_small, admin_input,
                               admin_message, admin_message_ok)

        present(window, canvas)

    daq.close()
    pygame.quit()
    sys.exit()
